language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gulp-cli
  - npm install -g codecov
  - npm install -g stryker
script:
  - gulp build
  - npm test
  - stryker run
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
